import tempfile
from pathlib import Path

import colour

from proimages.core.lut_gen.grade import apply_grade
from proimages.core.lut_gen.params import GradeParams

DEFAULT_LUT_SIZE = 33


def bake_lut(params: GradeParams, size: int = DEFAULT_LUT_SIZE) -> colour.LUT3D:
    table = apply_grade(colour.LUT3D.linear_table(size), params)
    comments = ["Generated by ProImages", f"schema_version {params.schema_version}"]
    if params.description:
        comments.append(params.description)
    return colour.LUT3D(table=table, name=params.name, comments=comments)


def bake_cube_file(params: GradeParams, path: str | Path, size: int = DEFAULT_LUT_SIZE) -> None:
    colour.write_LUT(bake_lut(params, size), str(path))


def bake_cube_text(params: GradeParams, size: int = DEFAULT_LUT_SIZE) -> str:
    """Bake to .cube text. colour.write_LUT only writes to a path, so round-trip a temp file."""
    with tempfile.NamedTemporaryFile(suffix=".cube", delete=False) as tmp:
        tmp_path = Path(tmp.name)
    try:
        bake_cube_file(params, tmp_path, size)
        return tmp_path.read_text()
    finally:
        tmp_path.unlink(missing_ok=True)
